### PR TITLE
Voice recording

### PR DESCRIPTION
**Pull request by htc36**
draft

### CODE REVIEW

**Comment by Mitri45** [comment]
Have a look through code and comments, plus I have added icon which requires attribution (https://www.flaticon.com/free-icon/download_1036561) so could be worth finding another one

**Comment by Mitri45** [comment]
I assume my next Task 4: Nga Kupu /Statistics modal - is using this modal as base, so I'll wait for this to be merged then I'll start Task 4.

**Comment by htc36** [comment]
Added error message, changed download icon, reviewed dmitriis changes

**Comment by htc36** [comment]
@Mitri45  the old girl is ready to go again. Accidentlly pushed this task aswell to this push request... oh well. 
https://www.notion.so/Statistics-Text-Changes-f0ffe6f6145a450a8233110bb63285b3

**Comment by Mitri45** [comment]
Ok, have a look later - I tried to get rid of the doubled setInterval - as they are both was doing the same thing and both was alive simultaneously, kinda a bit messy. I did refactoring by putting interval in the parent component, but resolution could be still messy  - have a look, maybe there is a better way to handle it. Otherwise merge it.

**Pull request merged**
