### PR TITLE
Share button for CardGame

### PR DESCRIPTION
**Pull request by Mitri45**
# What does this PR do: 
1. A lot of code moved around or deleted, but I saw a lot of improvements could be made. For this PR as well (like grouping same code from different places into reusable functions)
2. Cleaned unused styles in few components
3. Some renaming as per components/folders functionality 
4. LocalStorage now have two separate stats objects for games
5. Card game stores current time and the best time in localstorage
6. Modal now have decoupled footer with share and buy me a coffee button
7. Share button for card game copies the best time into clipboard (I assume content and format will be adjusted)
8. Stats modal now have two tabs for each game. (Statistics components could be refactored into <Layout> and <Data>)
9. Wordle Stats elements rearranged

### CODE REVIEW

**Comment by htc36** [comment]
Would be nice if user is on card game and they click on stats that it displays the tab for card game rather than defaulting to wordle (potentially they have never played the wordle game yet and might get confused)

**Comment by htc36** [comment]
un neccisary console.logs. 
image

**Comment by htc36** [comment]
ALso when copying to clipboard change "best time" to "last game time" or similar
image

**Comment by Mitri45** [comment]
@htc36 Once again a lot of moving pieces, so make a full test. Oh how would be good to have automated test now)

**Pull request merged**
